const en = {
  routesList: ["home", "about", "skills", "projects"],
  neofetchPanel: [
    ["About:", "Me"],
    ["Skills:", "JS, React, Java, C, SQL..."],
    ["Projects:", "Web Apps, AI, Parallel Programming"],
    ["Resume:", "Click for PDF"],
    ["Links:"],
  ],
  about: {
    general: ["General Commands Manual", "NAME"],
    synopsis: [
      "SYNOPSIS",
      "Hello,",
      "I'm",
      "Denis",
      "a computer engineering student focusing on web development.",
      "I am experienced with developing server-side apps and making responsive websites. I am in touch with newer technology, I love doing research and trying out new software.",
    ],
    overview: [
      "OVERVIEW",
      "Currently, I'm a ",
      "student at AYBU,",
      "pursuing a degree in ",
      "Computer Engineering.",
      "I am in my ",
      "fourth year",
      " of studies.",
    ],
    description: [
      "DESCRIPTION",
      "--i-am-a-tux-fan",
      "I am drawn to Linux-based operating systems and the freedom they provide.",
      "--i-am-a-cinephile",
      "I have always been fascinated by the direction and the cinematography of Soviet and Asian films.",
      "--i-am-a-gymrat",
      "For me, the process of setting and achieving goals through consistent training is rewarding both physically and mentally.",
    ],
  },
  skills: [
    [
      "Frontend",
      "React, Next.js",
      "I specialize in using React and Next.js for frontend development. I focus on creating responsive websites which have user-friendly interfaces that adapt seamlessly across devices. I also love working with TailwindCSS and Framer Motion because of the simplicity and effectiveness they provide.",
    ],
    [
      "Backend",
      "Express.js, ASP.NET, SQL",
      "I specialize in Express.js and have experience with Spring and ASP.NET. My expertise in SQL allows me to efficiently manage and query databases, ensuring seamless data handling. I am also able to implement secure authentication and authorization. Additionally, my passion for C amplifies my ability to optimize code for efficiency.",
    ],
    [
      "General",
      "Linux",
      "Linux has been pivotal in shaping my programming journey. Embracing the Linux environment not only expanded my technical capabilities but also transformed my approach to problem-solving. Linux systems has honed my understanding of computer architecture, file systems, and command-line operations, making me able to debug and optimize code with a deeper comprehension.",
    ],
  ],
  projects: [
    {
      mobileFileTitle: "portfolio",
      desktopFileTitle: "portfolio",
      title: "Portfolio Website",
      description: "This portfolio website made with React and Next.js.",
      url: "https://github.com/denis-the-menace/portfolio",
    },
    {
      mobileFileTitle: "bilinear_scaling",
      desktopFileTitle: "bilinear_scaling",
      title: "Bilinear Scaling",
      description: "Parallel program made in C for image scaling.",
      url: "https://github.com/denis-the-menace/mpi-image-scaling",
    },
    {
      mobileFileTitle: "nvidia_cuda",
      desktopFileTitle: "nvidia_cuda",
      title: "Bilinear Scaling with CUDA",
      description:
        "Parallel program made in C for image scaling using NVIDIA CUDA.",
      url: "https://github.com/denis-the-menace/cuda-image-scaling",
    },
    {
      mobileFileTitle: "chinese_chekers_ai",
      desktopFileTitle: "chinese_chekers_ai",
      title: "Chinese Checkers AI",
      description: "AI program made for understanding adversarial search.",
      url: "https://github.com/denis-the-menace",
    },
    {
      mobileFileTitle: "java_search_algo",
      desktopFileTitle: "java_search_algorithm",
      title: "DFS and BFS Maze Search",
      description: "Java program made to visualize DFS and BFS.",
      url: "https://github.com/denis-the-menace/DFS-BFS-Maze-Search",
    },
    {
      mobileFileTitle: "cli_todo_app",
      desktopFileTitle: "cli_todo_app",
      title: "CLI Todo App",
      description: "Simple CLI todo app made for my personal usage.",
      url: "https://github.com/denis-the-menace",
    },
    {
      mobileFileTitle: "veterinary_system",
      desktopFileTitle: "veterinary_system",
      title: "Veterinary System",
      description:
        "Veterinary system with authentication using JSON Web Token.",
      url: "https://github.com/denis-the-menace/Veterinary",
    },
    {
      mobileFileTitle: "ttol_game",
      desktopFileTitle: "two_truths_one_lie_game",
      title: "Two Truths One Lie Game",
      description:
        "Two truths one lie game where the questions are generated by ChatGPT.",
      url: "https://github.com/denis-the-menace",
    },
  ],
};

export default en;
