const tr = {
  routesList: ["ana_sayfa", "hakkımda", "beceriler", "projeler"],
  neofetchPanel: [
    ["Hakkımda", ""],
    ["Beceriler:", "JS, React, Java, C, SQL..."],
    ["Projeler:", "Web Uygulamaları, Yapay Zeka, Paralel Programlama"],
    ["CV:", "PDF için tıklayın"],
    ["Bağlantılar:"],
  ],
  about: {
    general: ["Genel Komut Kılavuzu", "İSİM"],
    synopsis: [
      "ÖZET",
      "Selam,",
      "Ben",
      "Denis",
      "web geliştirme üzerine odaklanan bir bilgisayar mühendisliği öğrencisiyim.",
      "Sunucu taraflı uygulamaları geliştirmek ve duyarlı web siteleri oluşturmak konusunda deneyimliyim. Yeni teknolojiyle ilgiliyim, araştırma yapmayı ve yeni yazılımlar denemeyi seviyorum.",
    ],
    overview: [
      "GENEL BAKIŞ",
      "Şu anda, ",
      "AYBÜ'de",
      "Bilgisayar Mühendisliği bölümünde ",
      "öğrenciyim.",
      "Öğrenim hayatımın ",
      "dördüncü yılındayım.",
    ],
    description: [
      "AÇIKLAMA",
      "--tux-fanatigi",
      "Linux tabanlı işletim sistemlerine ve sundukları özgürlüğe çekiliyorum.",
      "--sinema-gurusu",
      "Sovyet ve Asya filmlerinin yönetmenliği ve sinematografisi beni her zaman büyülemiştir.",
      "--gymrat",
      "Disiplinli antrenmanlarla birlikte hedefler belirleme ve bunlara ulaşma sürecini hem fiziksel hem de zihinsel olarak ödüllendirici buluyorum.",
    ],
  },
  skills: [
    [
      "Frontend",
      "React, Next.js, Tailwind",
      "Frontend geliştirme için React ve Next.js kullanıyorum. Cihazlar arasında sorunsuz bir şekilde uyum sağlayan, kullanıcı dostu arayüzlere sahip duyarlı web siteleri oluşturmaya odaklanıyorum. Sağladıkları basitlik ve verimlilik nedeniyle TailwindCSS ve Framer Motion ile çalışmayı da seviyorum.",
    ],
    [
      "Backend",
      "Express.js, ASP.NET, SQL",
      "Backend için Express.js kullanmayı tercih ediyorum, ek olarak Spring ve ASP.NET deneyimim var. SQL bilgim veritabanlarını verimli bir şekilde yönetmemi ve verileri sorunsuz bir şekilde işlememi sağlıyor. Ayrıca, güvenli authentication ve authorization deneyimim var. Bunun yanı sıra, C'ye olan tutkum, kodu optimize etme yeteneğimi arttırıyor.",
    ],
    [
      "Genel",
      "Linux",
      "Linux, programlama yolculuğumu şekillendirmede önemli bir rol oynadı. Linux ortamını benimsemek teknik yeteneklerimi geliştirmekle kalmadı, aynı zamanda problem çözme yaklaşımımı da değiştirdi. Linux sistemleri bilgisayar mimarisi, dosya sistemleri ve terminal işlemlerine ilişkin anlayışımı geliştirerek kodu daha derin bir anlayışla debug ve optimize etme kabiliyeti kazanmamı sağladı.",
    ],
  ],
  projects: [
    {
      mobileFileTitle: "portfolio",
      desktopFileTitle: "portfolio",
      title: "Portfolio Website",
      description: "This portfolio website made with React and Next.js.",
      url: "https://github.com/denis-the-menace/portfolio",
    },
    {
      mobileFileTitle: "bilinear_scaling",
      desktopFileTitle: "bilinear_scaling",
      title: "Bilinear Scaling",
      description: "Parallel program made in C for image scaling.",
      url: "https://github.com/denis-the-menace",
    },
    {
      mobileFileTitle: "nvidia_cuda",
      desktopFileTitle: "nvidia_cuda",
      title: "Bilinear Scaling with CUDA",
      description:
        "Parallel program made in C for image scaling using NVIDIA CUDA.",
      url: "https://github.com/denis-the-menace",
    },
    {
      mobileFileTitle: "chinese_chekers_ai",
      desktopFileTitle: "chinese_chekers_ai",
      title: "Chinese Checkers AI",
      description: "AI program made for understanding adversarial search.",
      url: "https://github.com/denis-the-menace",
    },
    {
      mobileFileTitle: "java_search_algo",
      desktopFileTitle: "java_search_algorithm",
      title: "DFS and BFS Maze Search",
      description: "Java program made to visualize DFS and BFS.",
      url: "https://github.com/denis-the-menace/DFS-BFS-Maze-Search",
    },
    {
      mobileFileTitle: "cli_todo_app",
      desktopFileTitle: "cli_todo_app",
      title: "CLI Todo App",
      description: "Simple CLI todo app made for my personal usage.",
      url: "https://github.com/denis-the-menace",
    },
    {
      mobileFileTitle: "veterinary_system",
      desktopFileTitle: "veterinary_system",
      title: "Veterinary System",
      description:
        "Veterinary system with authentication using JSON Web Token.",
      url: "https://github.com/denis-the-menace/Veterinary",
    },
    {
      mobileFileTitle: "ttol_game",
      desktopFileTitle: "two_truths_one_lie_game",
      title: "Two Truths One Lie Game",
      description:
        "Two truths one lie game where the questions are generated by ChatGPT.",
      url: "https://github.com/denis-the-menace",
    },
  ],
};
export default tr;
